WolfAC_Table = {

    BlacklistWeapon = {
        "WEAPON_MINIGUN",
        "WEAPON_RAILGUN",
        "WEAPON_RAYMINIGUN",
        "WEAPON_RAYCARBINE",
        "WEAPON_STICKYBOMB",
        "WEAPON_GRENADE",
        "WEAPON_RPG",
        "WEAPON_GRENADELAUNCHER",
        "WEAPON_HEAVYSNIPER",
        "WEAPON_HEAVYSNIPER_MK2",
        "WEAPON_SNIPERRIFLE"
    },

    BlacklistVehicle = {
        "lazer", "cargobob", "cargoplane", "oppressor", "deluxo"
    },

    BlacklistWords = {"duce", "negro", "putanna", "fuck"},

    BlacklistNameSteam = {
        "duce",
        "admin",
        "administartor",
        "negro"
    },

    BlacklistObject = {
        "stt_prop_ramp_jump_xxl",
		"stt_prop_ramp_multi_loop_rb",
		"stt_prop_ramp_spiral_l",
		"stt_prop_ramp_spiral_l_l",
		"stt_prop_ramp_spiral_l_m",
		"stt_prop_ramp_spiral_l_s",
		"stt_prop_ramp_spiral_l_xxl",
		"stt_prop_ramp_spiral_m",
		"stt_prop_ramp_spiral_s",
		"stt_prop_ramp_spiral_xxl",
		"stt_prop_stunt_track_dwslope45",
		"stt_prop_stunt_track_dwslope30",
		"stt_prop_stunt_track_dwslope15",
		"stt_prop_stunt_soccer_ball",
		"prop_ld_container",
		"prop_container_hole",
		"prop_container_05a",
		"stt_prop_stunt_bowling_ball",
		"prop_fnclink_05crnr1",
		"xs_prop_hamburgher_wl",
		"xs_prop_plastic_bottle_wl",
		"prop_windmill_01",
		"p_spinning_anus_s",
		"stt_prop_ramp_adj_flip_m",
		"stt_prop_ramp_adj_flip_mb",
		"stt_prop_ramp_adj_flip_s",
		"stt_prop_ramp_adj_flip_sb",
		"stt_prop_ramp_adj_hloop",
		"stt_prop_ramp_adj_loop",
		"stt_prop_ramp_jump_l",
		"stt_prop_ramp_jump_m",
		"stt_prop_ramp_jump_s",
		"stt_prop_ramp_jump_xl",
		"stt_prop_ramp_jump_xs",
        "prop_container_01b",
		"prop_container_01g",
		"prop_container_01a",
		"prop_container_01e",
		"prop_container_01h",
		"prop_container_01mb",
		"prop_container_01c",
		"prop_container_ld_d",
		"prop_container_02a",
		"prop_container_01d"
    },

    BlacklistPeds = {
        "a_m_m_acult_01",
        "s_m_y_swat_01",
        "a_m_o_acult_01",
        "ig_wade",
        "s_m_y_hwaycop_01",
        "A_M_Y_ACult_01",
        's_m_m_movalien_01',
        's_m_m_movallien_01',
        'u_m_y_babyd',
        'CS_Orleans',
        'A_M_Y_ACult_01',
        'S_M_M_MovSpace_01',
        'U_M_Y_Zombie_01',
    },

    BlackListExplosions = {
		[0] = { name = "Grenade", ban = true, deletevent = true, max = 1},
        [1] = { name = "GrenadeLauncher", ban = true, deletevent = true, max = 1},
        [2] = { name = "PipeBoomb", ban = true, deletevent = true, max = 1},
        [3] = { name = "PipeBoomb", ban = true, deletevent = true, max = 1},
        [4] = { name = "Motolov", ban = true, deletevent = true, max = 1},
        [5] = { name = "TankShell", ban = true, deletevent = true, max = 1},
        [6] = { name = "Hi_Octane", ban = true, deletevent = true, max = 1},
        [7] = { name = "Car", ban = true, deletevent = true, max = 1},
        [8] = { name = "Plance", ban = true, deletevent = true, max = 1},
        [9] = { name = "PetrolPump", ban = true, deletevent = true, max = 1},
        [10] = { name = "Bike", ban = false, deletevent = true, max = 1},
		[11] = { name = "Dir_Steam", ban = false, deletevent = true, max = 1},
		[12] = { name = "Dir_Flame", ban = false, deletevent = true, max = 1},
		[13] = { name = "Dir_Water_Hydrant", ban = false , deletevent = true, max = 1},
		[14] = { name = "Dir_Gas_Canister", ban = false, deletevent = true, max = 1},
		[15] = { name = "Boat", ban = false, deletevent = true, max = 1},
		[16] = { name = "Ship_Destroy", ban = false, deletevent = true, max = 1},
        [17] = { name = "Truck", ban = false, deletevent = true, max = 1},
		[18] = { name = "Bullet", ban = false, deletevent = true, max = 1},
		[19] = { name = "SmokeGrenadeLauncher", ban = true, deletevent = true, max = 1},
		[20] = { name = "SmokeGrenade", ban = true, deletevent = true, max = 1},
		[21] = { name = "BZGAS", ban = true, deletevent = true, max = 1},
		[22] = { name = "Flare", ban = true, deletevent = true, max = 1},
		[23] = { name = "Gas_Canister", ban = false, deletevent = true, max = 1},
		[24] = { name = "Extinguisher", ban = false, deletevent = true, max = 1},
		[25] = { name = "Programmablear", ban = false, deletevent = true, max = 1},
		[26] = { name = "Train", ban = false, deletevent = true, max = 1},
		[27] = { name = "Barrel", ban = false, deletevent = true, max = 1},
		[28] = { name = "PROPANE", ban = false, deletevent = true, max = 1},
		[29] = { name = "Blimp", ban = false, deletevent = true, max = 1},
		[30] = { name = "Dir_Flame_Explode", ban = false, deletevent = true, max = 1},
		[31] = { name = "Tanker", ban = false, deletevent = true, max = 1},
		[32] = { name = "PlaneRocket", ban = false, deletevent = true, max = 1},
		[34] = { name = "Gas_Tank", ban = false, deletevent = true, max = 1},
		[33] = { name = "VehicleBullet", ban = true, deletevent = true, max = 1},
		[35] = { name = "FireWork", ban = true, deletevent = true, max = 1},
		[36] = { name = "SnowBall", ban = false, deletevent = true, max = 1},
		[37] = { name = "ProxMine", ban = true, deletevent = true, max = 1},
		[38] = { name = "Valkyrie_Cannon", ban = true, deletevent = true, max = 1},
    },

    WeaponDamages = {
        [-1357824103] = { damage = 34, name = "AdvancedRifle"},
        [453432689] = { damage = 26, name = "Pistol"},
        [1593441988] = { damage = 27, name = "CombatPistol"},
        [584646201] = { damage = 25, name = "APPistol"},
        [-1716589765] = { damage = 51, name = "Pistol50"},
        [-1045183535] = { damage = 160, name = "Revolver"},
        [-1076751822] = { damage = 28, name = "SNSPistol"},
        [-771403250] = { damage = 40, name = "HeavyPistol"},
        [137902532] = { damage = 34, name = "VintagePistol"},
        [324215364] = { damage = 21, name = "MicroSMG"},
        [736523883] = { damage = 22, name = "SMG"},
        [-270015777] = { damage = 23, name = "AssaultSMG"},
        [-1121678507] = { damage = 22, name = "MiniSMG"},
        [-619010992] = { damage = 27, name = "MachinePistol"},
        [171789620] = { damage = 22, name = "CombatPDW"},
        [487013001] = { damage = 58, name = "PumpShotgun"},
        [2017895192] = { damage = 40, name = "SawnoffShotgun"},
        [-494615257] = { damage = 32, name = "AssaultShotgun"},
        [-1654528753] = { damage = 14, name = "BullpupShotgun"},
        [984333226] = { damage = 117, name = "HeavyShotgun"},
        [-1074790547] = { damage = 30, name = "AssaultRifle"},
        [-2084633992] = { damage = 32, name = "CarbineRifle"},
        [-1063057011] = { damage = 32, name = "SpecialCarbine"},
        [2132975508] = { damage = 32, name = "BullpupRifle"},
        [1649403952] = { damage = 34, name = "CompactRifle"},
        [-1660422300] = { damage = 40, name = "MG"},
        [2144741730] = { damage = 45, name = "CombatMG"},
        [1627465347] = { damage = 34, name = "Gusenberg"},
        [100416529] = { damage = 101, name = "SniperRifle"},
        [205991906] = { damage = 216, name = "HeavySniper"},
        [-952879014] = { damage = 65, name = "MarksmanRifle"},
        [1119849093] = { damage = 30, name = "Minigun"},
        [-1466123874] = { damage = 165, name = "Musket"},
        [911657153] = { damage = 1, name = "StunGun"},
        [1198879012] = { damage = 10, name = "FlareGun"},
        [-598887786] = { damage = 220, name = "MarksmanPistol"},
        [1834241177] = { damage = 30, name = "Railgun"},
        [-275439685] = { damage = 30, name = "DoubleBarrelShotgun"},
        [-1746263880] = { damage = 81, name = "Double Action Revolver"},
        [-2009644972] = { damage = 30, name = "SNS Pistol Mk II"},
        [-879347409] = { damage = 200, name = "Heavy Revolver Mk II"},
        [-1768145561] = { damage = 32, name = "Special Carbine Mk II"},
        [-2066285827] = { damage = 33, name = "Bullpup Rifle Mk II"},
        [1432025498] = { damage = 32, name = "Pump Shotgun Mk II"},
        [1785463520] = { damage = 75, name = "Marksman Rifle Mk II"},
        [961495388] = { damage = 40, name = "Assault Rifle Mk II"},
        [-86904375] = { damage = 33, name = "Carbine Rifle Mk II"},
        [-608341376] = { damage = 47, name = "Combat MG Mk II"},
        [177293209] = { damage = 230, name = "Heavy Sniper Mk II"},
        [-1075685676] = { damage = 32, name = "Pistol Mk II"},
        [2024373456] = { damage = 25, name = "SMG Mk II"}
    },

    AntiSpamTriggerList = {
        { event = "esx_billing:sendBill" , max = 3 },
    }

}